export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";

export const GET_PRODUCTS_ID_REQUEST = "GET_PRODUCTS_ID_REQUEST";
export const GET_PRODUCTS_ID_SUCCESS = "GET_PRODUCTS_ID_SUCCESS";
export const GET_PRODUCTS_ID_FAILURE = "GET_PRODUCTS_ID_FAILURE";

export const ADD_PRODUCTS_REQUEST = "ADD_PRODUCTS_REQUEST";
export const ADD_PRODUCTS_SUCCESS = "ADD_PRODUCTS_SUCCESS";
export const ADD_PRODUCTS_FAILURE = "ADD_PRODUCTS_FAILURE";

export const EDIT_PRODUCTS_REQUEST = "EDIT_PRODUCTS_REQUEST";
export const EDIT_PRODUCTS_SUCCESS = "EDIT_PRODUCTS_SUCCESS";
export const EDIT_PRODUCTS_FAILURE = "EDIT_PRODUCTS_FAILURE";

export const DELETE_PRODUCTS_REQUEST = "DELETE_PRODUCTS_REQUEST";
export const DELETE_PRODUCTS_SUCCESS = "DELETE_PRODUCTS_SUCCESS";
export const DELETE_PRODUCTS_FAILURE = "DELETE_PRODUCTS_FAILURE";